version: "3"
services:
    mongo:
        container_name: docker_mongo
        image: mongo
        restart: always
        volumes: 
            - database:/data/db
        ports:
        - "27017:27017"
    app:
        build: 
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - "8085:8080"
        links:
            - mongo
volumes:
    database: